services:
  anythingllm:
    image: mintplexlabs/anythingllm:1.8.0
    container_name: anythingllm
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_BASE_PATH=http://ollama:11434
      - VECTOR_DB=lancedb
      - LANCE_DB_PATH=/app/server/storage/vector-storage
      - UID=1000
      - GID=1000
      - STORAGE_DIR=/app/server/storage
      - NODE_ENV=production
      - SERVER_PORT=3000
      - DATABASE_CLIENT=sqlite3
      - DATABASE_URL=/app/server/storage/anythingllm.db
    volumes:
      - ./data/anythingllm/storage:/app/server/storage
      - ./data/anythingllm/data:/app/server/data
      - ./data/anythingllm/logs:/app/server/logs
    depends_on:
      - ollama
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/ollama", "serve"]
    command: null